"use client";

import GlobalStyle from "./styles/globalStyles";
import "./globals.css";
import NightSky from "../components/nightsky";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <NightSky />
        {children}
      </body>
    </html>
  );
}
