"use client";

import GlobalStyle from "./styles/globalStyles";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
}
